In [11]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:

from mgnifyapi import download_studies
#from mgnifyapi import retrieve_metadata
import matplotlib.pyplot as plt
import pandas as pd
import os
import json

from mgnifyapi.retrieve_metadata import analyses_json_to_df, studies_json_to_df
from mgnifyapi import preprocessing

In [155]:
outpath = "output"
study_id = "MGYS00005435"


file_list = preprocessing.retrieve_abund_filenames(
    os.path.join(outpath, study_id), 
    study_id, 
    phylum_files=True, 
)

In [ ]:
preprocessing.filter_abund_vers(file_list)

TypeError: filter_abund_vers() missing 1 required positional argument: 'file_list'

In [67]:
something = False
if not something:
    print('what')

what

First, getting information about the biomes. What studies are there? 

Getting from "root" biome > engineered > wastewater

In [44]:
ranks = ['Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']

well = enumerate(ranks)

In [48]:
# store only the deepest ranks 
existing = ['Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Species']

tracker = 0
deepest = 'Genus'
for i, rank in enumerate(ranks):

    if (rank in existing) & (i > tracker):
        tracker = i
        deepest = rank

print(i, deepest)

7 Species

In [37]:
ok = pd.read_csv("output/df_analyses.csv")
ok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1772 entries, 0 to 1771
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   analysis_id          1772 non-null   object
 1   sample_id            1772 non-null   object
 2   assembly_run_id      1772 non-null   object
 3   experiment_type      1772 non-null   object
 4   pipeline_version     1772 non-null   float64
 5   study_id             1772 non-null   object
 6   instrument_platform  1772 non-null   object
 7   sample_name          1673 non-null   object
 8   biosample            1673 non-null   object
 9   sample_description   1673 non-null   object
 10  latitude             1595 non-null   float64
 11  longitude            1596 non-null   float64
 12  geolocation          1289 non-null   object
 13  biome                423 non-null    object
 14  biome_feature        503 non-null    object
 15  biome_material       503 non-null    object
dtypes: float64(3), object(13)
memory usage: 221.6+ KB

In [42]:
ok.query(f'study_id == "{ok.study_id[0]}"').shape

(6, 16)

In [40]:
# also resturns as a json
# study_info = get_biome_info.get_studies_info(
#     biome_name = "root:Engineered:Wastewater",
#     outpath="output-test3"
# )

# get df
df_studies_mgnify = get_biome_info.studies_json_to_df(
    outpath="output-test"
)

df_studies_mgnify.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_id     186 non-null    object
 1   study_name   186 non-null    object
 2   n_samples    186 non-null    int64
 3   bioproject   184 non-null    object
 4   centre_name  186 non-null    object
 5   biomes       186 non-null    object
dtypes: int64(1), object(5)
memory usage: 8.8+ KB

In [12]:
df_analyses_mgnify = get_biome_info.analyses_json_to_df(
    outpath="output-test3"
)
df_analyses_mgnify.head()

,analysis_id,sample_id,assembly_run_id,experiment_type,pipeline_version,study_id,instrument_platform
0,MGYA00571601,ERS3742479,ERZ1505403,assembly,5.0,MGYS00005614,Illumina HiSeq 4000
1,MGYA00571602,ERS3742474,ERZ1505402,assembly,5.0,MGYS00005614,Illumina HiSeq 4000
2,MGYA00571603,ERS3742480,ERZ1505400,assembly,5.0,MGYS00005614,Illumina HiSeq 4000
3,MGYA00572443,ERS3742475,ERZ1505401,assembly,5.0,MGYS00005614,Illumina HiSeq 4000
4,MGYA00572444,ERS3742477,ERZ1505399,assembly,5.0,MGYS00005614,Illumina HiSeq 4000

In [57]:
# notice that there are more study ids here then there are in the analysis 
print(
    df_studies_mgnify['study_id'].nunique(),
    df_analyses_mgnify['study_id'].nunique()
)

186 114

In [15]:
study_info = get_biome_info.studies_json_to_df("output-test/mgnify_studies.json")
analyses_info = get_biome_info.analyses_json_to_df("output-test3/mgnify_analyses.json")

df_analysis, df_study = get_biome_info.get_studies_and_analyses_dfs(
    study_info,
    analyses_info
)

df_analysis.head()

,analysis_id,sample_id,assembly_run_id,experiment_type,pipeline_version,instrument_platform,study_id,bioproject,study_name,n_samples,centre_name,biomes
0,MGYA00571601,ERS3742479,ERZ1505403,assembly,5.0,Illumina HiSeq 4000,MGYS00005614,PRJEB39978,EMG produced TPA metagenomics assembly of PRJE...,8,EMG,root:Engineered:Wastewater
1,MGYA00571602,ERS3742474,ERZ1505402,assembly,5.0,Illumina HiSeq 4000,MGYS00005614,PRJEB39978,EMG produced TPA metagenomics assembly of PRJE...,8,EMG,root:Engineered:Wastewater
2,MGYA00571603,ERS3742480,ERZ1505400,assembly,5.0,Illumina HiSeq 4000,MGYS00005614,PRJEB39978,EMG produced TPA metagenomics assembly of PRJE...,8,EMG,root:Engineered:Wastewater
3,MGYA00572443,ERS3742475,ERZ1505401,assembly,5.0,Illumina HiSeq 4000,MGYS00005614,PRJEB39978,EMG produced TPA metagenomics assembly of PRJE...,8,EMG,root:Engineered:Wastewater
4,MGYA00572444,ERS3742477,ERZ1505399,assembly,5.0,Illumina HiSeq 4000,MGYS00005614,PRJEB39978,EMG produced TPA metagenomics assembly of PRJE...,8,EMG,root:Engineered:Wastewater

In [64]:
df_analysis.groupby(['instrument_platform', ])['experiment_type'].nunique().reset_index().sort_values('experiment_type', ascending=False)

             instrument_platform  experiment_type
3            Illumina HiSeq 1500                2
4            Illumina HiSeq 2000                2
5            Illumina HiSeq 2500                2
6            Illumina HiSeq 3000                2
7            Illumina HiSeq 4000                2
9                 Illumina MiSeq                2
11                        MinION                2
0                    HiSeq X Ten                1
1    Illumina Genome Analyzer II                1
2   Illumina Genome Analyzer IIx                1
8            Illumina Hiseq 2000                1
10         Illumina NovaSeq 6000                1
12                   NextSeq 500                1
13                   unspecified                1

In [72]:
metagenome_studies = df_analysis['study_id'].unique()
metagenome_studies = metagenome_studies.tolist()
up_to = metagenome_studies.index("MGYS00004939")
new_metagenome_studies = metagenome_studies[up_to+1:]
len(new_metagenome_studies)

43

In [73]:
for study_id in new_metagenome_studies:
    study_info = download_studies.get_results_info_from_MGnifystudy(
        study_id
    )
    study_results = download_studies.process_study_results(
        summary_results_study=study_info,
        download_folder="output-test2/metagenome",
        study_accession=study_id
    )

Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004940/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004940
Processing results for the MGnify study:
File 'MGYS00004940_ERP112627_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
File 'MGYS00004940_ERP112627_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004940'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004948/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004948
Processing results for the MGnify study:
File 'MGYS00004948_ERP112635_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
File 'MGYS00004948_ERP112635_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004948'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004949/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004949
Processing results for the MGnify study:
File 'MGYS00004949_ERP112636_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
File 'MGYS00004949_ERP112636_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004949'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004983/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004983
Processing results for the MGnify study:
File 'MGYS00004983_ERP112874_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
File 'MGYS00004983_ERP112874_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004983'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004985/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004985
Processing results for the MGnify study:
File 'MGYS00004985_ERP112879_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
File 'MGYS00004985_ERP112879_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004985'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004989/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004989
Processing results for the MGnify study:
File 'MGYS00004989_ERP112891_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
File 'MGYS00004989_ERP112891_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004989'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00004999/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00004999
Processing results for the MGnify study:
File 'MGYS00004999_ERP111004_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
File 'MGYS00004999_ERP111004_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00004999'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005001/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005001
Processing results for the MGnify study:
File 'MGYS00005001_ERP112198_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
File 'MGYS00005001_ERP112198_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005001'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005002/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005002
Processing results for the MGnify study:
File 'MGYS00005002_ERP112199_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
File 'MGYS00005002_ERP112199_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005002'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005006/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005006
Processing results for the MGnify study:
File 'MGYS00005006_ERP112577_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
File 'MGYS00005006_ERP112577_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005006'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005011/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005011
Processing results for the MGnify study:
File 'MGYS00005011_ERP112200_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
File 'MGYS00005011_ERP112200_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005011'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005016/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005016
Processing results for the MGnify study:
File 'MGYS00005016_ERP112202_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
File 'MGYS00005016_ERP112202_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005016'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005025/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005025
Processing results for the MGnify study:
File 'MGYS00005025_ERP112252_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
File 'MGYS00005025_ERP112252_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005025'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00002058/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00002058
Processing results for the MGnify study:
File 'MGYS00002058_ERP104231_GO-slim_abundances_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_GO_abundances_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_IPR_abundances_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_phylum_taxonomy_abundances_SSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_taxonomy_abundances_SSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_phylum_taxonomy_abundances_LSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_taxonomy_abundances_LSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_diversity_LSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_diversity_SSU_v4.0.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
File 'MGYS00002058_ERP104231_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00002058'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005035/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005035
Processing results for the MGnify study:
File 'MGYS00005035_ERP110969_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
File 'MGYS00005035_ERP110969_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005035'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005046/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005046
Processing results for the MGnify study:
File 'MGYS00005046_ERP108535_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
File 'MGYS00005046_ERP108535_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005046'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005055/downloads
GET request successful.
Study directory created: output-test2/metagenome/MGYS00005055
Processing results for the MGnify study:
File 'MGYS00005055_ERP110973_GO-slim_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_GO_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_IPR_abundances_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_phylum_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_taxonomy_abundances_SSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_phylum_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
File 'MGYS00005055_ERP110973_taxonomy_abundances_LSU_v4.1.tsv' downloaded and saved in 'output-test2/metagenome/MGYS00005055'.
Making GET request to: https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00005056/downloads
GET request successful.